#!/usr/bin/env python
WALL_SIZE = 10
ROAD_WIDTH = 220
ROTATE_SPACE = 300
STRAIGHT_AREA = 300

ZERO = 0
OFFSET = 1

SCREEN_WIDTH = 4*WALL_SIZE + 4*ROAD_WIDTH + 2*ROTATE_SPACE + STRAIGHT_AREA
SCREEN_HEIGHT = 4*WALL_SIZE + 3*ROAD_WIDTH

GOAL_PICT = [ROAD_WIDTH+WALL_SIZE,WALL_SIZE]
GOAL_ANGLE = 0

LOGO_POSI = [(SCREEN_WIDTH/2)-108,(5*SCREEN_HEIGHT/6)-28]
LOGO_ANGLE = 0

INIT_POSITION = [3.5, 1.15]
INIT_ANGLE = 0.0

ADD = 100

OBS = [
    [ZERO, ZERO, SCREEN_WIDTH, WALL_SIZE],
    [ZERO, WALL_SIZE, WALL_SIZE, SCREEN_HEIGHT - WALL_SIZE],
    [WALL_SIZE, SCREEN_HEIGHT - WALL_SIZE, SCREEN_WIDTH - WALL_SIZE, WALL_SIZE],
    [SCREEN_WIDTH - WALL_SIZE, WALL_SIZE, WALL_SIZE, SCREEN_HEIGHT - 2*WALL_SIZE],

    [WALL_SIZE+ROAD_WIDTH, WALL_SIZE+ROAD_WIDTH, SCREEN_WIDTH-2*(WALL_SIZE+ROAD_WIDTH), WALL_SIZE],

    [WALL_SIZE+ROAD_WIDTH, WALL_SIZE+ROAD_WIDTH, WALL_SIZE, SCREEN_HEIGHT-2*(WALL_SIZE+ROAD_WIDTH)],
    [WALL_SIZE+ROAD_WIDTH+ROTATE_SPACE, WALL_SIZE+ROAD_WIDTH, WALL_SIZE, SCREEN_HEIGHT-2*(WALL_SIZE+ROAD_WIDTH)],
    [2*WALL_SIZE+ROAD_WIDTH, SCREEN_HEIGHT-(2*WALL_SIZE+ROAD_WIDTH), ROTATE_SPACE, WALL_SIZE],

    [SCREEN_WIDTH-(2*WALL_SIZE+ROAD_WIDTH), WALL_SIZE+ROAD_WIDTH, WALL_SIZE, SCREEN_HEIGHT-2*(WALL_SIZE+ROAD_WIDTH)],
    [SCREEN_WIDTH-(2*WALL_SIZE+ROAD_WIDTH+ROTATE_SPACE), WALL_SIZE+ROAD_WIDTH, WALL_SIZE, SCREEN_HEIGHT-2*(WALL_SIZE+ROAD_WIDTH)],
    [SCREEN_WIDTH-(WALL_SIZE+ROAD_WIDTH+ROTATE_SPACE), SCREEN_HEIGHT-(2*WALL_SIZE+ROAD_WIDTH), ROTATE_SPACE, WALL_SIZE],

    [2*(WALL_SIZE+ROAD_WIDTH)+ROTATE_SPACE, 2*(WALL_SIZE+ROAD_WIDTH), STRAIGHT_AREA, WALL_SIZE],
    [SCREEN_WIDTH - (2*(WALL_SIZE+ROAD_WIDTH)+ROTATE_SPACE+WALL_SIZE), SCREEN_HEIGHT-(WALL_SIZE+ROAD_WIDTH), WALL_SIZE, ROAD_WIDTH],
    [(2*(WALL_SIZE+ROAD_WIDTH)+ROTATE_SPACE), SCREEN_HEIGHT-(WALL_SIZE+ROAD_WIDTH), WALL_SIZE, ROAD_WIDTH],

    [SCREEN_WIDTH/3, WALL_SIZE, 30, ROAD_WIDTH*0.4],
    [2*(SCREEN_WIDTH/3), WALL_SIZE, 30, ROAD_WIDTH*0.4],
    [SCREEN_WIDTH/2, WALL_SIZE+ROAD_WIDTH-(ROAD_WIDTH*0.4), 30, ROAD_WIDTH*0.4],
]

WARP_ANGLE = 0.0

WARP = [
]

GOAL = [
   [ROAD_WIDTH+WALL_SIZE, WALL_SIZE+OFFSET, 2*(WALL_SIZE+OFFSET), ROAD_WIDTH]
]
