#!/usr/bin/env python
SCREEN_WIDTH = 1860
SCREEN_HEIGHT = 1025
ROAD_WIDTH = 220

WALL_SIZE = 10
GOAL_WALL_SIZE = 100

SIDE_WALL_SIZE = 10 
COURSE_WALL_SIZE = WALL_SIZE 
STARTING_COORD1 = SCREEN_HEIGHT/3
STARTING_COORD2 = SCREEN_WIDTH - STARTING_COORD1
STARTING_COORD3 = SCREEN_HEIGHT*2/3

START_X = 0
START_Y = 0
START_WIDTH = WALL_SIZE
START_HEIGHT = STARTING_COORD1

GOAL_PICT = [SCREEN_WIDTH-(ROAD_WIDTH+WALL_SIZE)+10, SCREEN_HEIGHT - (WALL_SIZE+110)]
GOAL_ANGLE = 1

G = 245 + 81

INIT_POSITION = [1.2, 8.95]
INIT_ANGLE = 90.0

LOGO_POSI = [340,400]
LOGO_ANGLE = 0

levelup = True

OBS = [
   [   0,   0, WALL_SIZE  , SCREEN_HEIGHT ],
   [   0,   0, SCREEN_WIDTH, WALL_SIZE  ],
   [ SCREEN_WIDTH-WALL_SIZE,  WALL_SIZE, WALL_SIZE  , SCREEN_HEIGHT - 2*WALL_SIZE ],
   [  WALL_SIZE, SCREEN_HEIGHT-WALL_SIZE, SCREEN_WIDTH, WALL_SIZE  ],
   [ WALL_SIZE + 1*ROAD_WIDTH + G*0, WALL_SIZE + ROAD_WIDTH, G, SCREEN_HEIGHT - (2*WALL_SIZE + ROAD_WIDTH) ],
   [ WALL_SIZE + 2*ROAD_WIDTH + G*1, WALL_SIZE,              G, SCREEN_HEIGHT - (2*WALL_SIZE + ROAD_WIDTH) ],
   [ WALL_SIZE + 3*ROAD_WIDTH + G*2, WALL_SIZE + ROAD_WIDTH, G, SCREEN_HEIGHT - (2*WALL_SIZE + ROAD_WIDTH) ]
]

if levelup:
   P = (SCREEN_HEIGHT - 2*(WALL_SIZE+ROAD_WIDTH)) / 3
   Y1 = (WALL_SIZE+ROAD_WIDTH) + P
   Y2 = (WALL_SIZE+ROAD_WIDTH) + 2*P
   OW = ROAD_WIDTH*0.35
   OBS.append([WALL_SIZE+ROAD_WIDTH*0,             Y2, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*1 + 0*G - OW,  Y1, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*1 + 1*G,       Y1, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*2 + 1*G - OW,  Y2, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*2 + 2*G     ,  Y2, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*3 + 2*G - OW,  Y1, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*3 + 3*G     ,  Y1, OW, 30])
   OBS.append([WALL_SIZE+ROAD_WIDTH*4 + 3*G - OW,  Y2, OW, 30])

WARP_ANGLE = 90.0

WARP = [
    [WALL_SIZE + 3*ROAD_WIDTH + G*3, SCREEN_HEIGHT - (WALL_SIZE + 38), 220, 22],
    [WALL_SIZE, SCREEN_HEIGHT - (WALL_SIZE + 38), 220, 22]
]

GOAL = [
   [WALL_SIZE + 3*ROAD_WIDTH + G*3, SCREEN_HEIGHT - (WALL_SIZE + 110), 220, 22],
   [WALL_SIZE, SCREEN_HEIGHT - (WALL_SIZE + 110), 220, 22]
]
